name: flickpedia
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-345.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: any 
  path_provider: any 
  path: ^1.8.1
  sqflite: ^2.0.3
  http: ^1.1.0
  get_it: ^7.2.0
  intl: any 
  injectable: ^2.3.0
  draggable_home: any 
  flutter_rating_bar: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true
